import AppKit
import CryptoKit

enum ClipKind: String, Codable {
    case text
    case image
}

struct Clip: Codable {
    var digest: String
    var kind: ClipKind
    var bytes: Int
    var lastUnix: Int64
    var uses: UInt64
    var preview: String

    var file: String {
        "\(digest).\(kind == .text ? "txt" : "png")"
    }
}

enum Clips {
    static let previewLimit = 4096
    static let freshSeconds: Int64 = 48 * 3600
    static let halfLifeDays = 7.0
    static let floor = 0.05
    static let budget = 80 << 20

    static func query(_ needle: String, clips: [Clip]) -> [Clip] {
        let recent = clips.sorted { $0.lastUnix == $1.lastUnix ? $0.digest < $1.digest : $0.lastUnix > $1.lastUnix }
        let target = Array(lowercase(trim(needle)).utf8)
        guard !target.isEmpty else { return recent }
        return recent.filter { Array(lowercase($0.preview).utf8).firstRange(of: target) != nil }
    }

    static func score(_ clip: Clip, now: Int64) -> Double {
        let days = max(Double(now &- clip.lastUnix) / 86400, 0)
        return log(1 + Double(clip.uses)) * exp(-days / halfLifeDays)
    }

    static func retained(_ clips: [Clip], now: Int64) -> [Clip] {
        let kept = clips.filter { now &- $0.lastUnix < freshSeconds || ($0.uses > 1 && score($0, now: now) >= floor) }
        var total = kept.reduce(0) { $0 + $1.bytes }
        guard total > budget else { return kept }
        var dropped: Set<String> = []
        for clip in kept.sorted(by: { density($0, now: now) < density($1, now: now) }) where total > budget {
            dropped.insert(clip.digest)
            total -= clip.bytes
        }
        return kept.filter { !dropped.contains($0.digest) }
    }

    static func preview(_ text: String) -> String {
        var out = String.UnicodeScalarView()
        for word in text.unicodeScalars.split(whereSeparator: {
            $0.properties.isWhitespace || $0.value < 0x20 || $0.value == 0x7F
        }) {
            if !out.isEmpty { out.append(" ") }
            out.append(contentsOf: word)
            if out.count >= previewLimit {
                return String(out.prefix(previewLimit))
            }
        }
        return String(out)
    }

    private static func density(_ clip: Clip, now: Int64) -> Double {
        score(clip, now: now) / Double(max(1, clip.bytes))
    }
}

@MainActor
final class Clipboard {
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "public.file-url",
    ]
    private static let indexFile = "index.json"
    private static let blobDir = "blobs"
    private static let interval = 0.5
    private static let copyKey: CGKeyCode = 0x08
    private static let pasteKey: CGKeyCode = 0x09
    private static let copyTries = 15

    private let dir: URL
    private var items: [Clip] = []
    private var seen = NSPasteboard.general.changeCount
    private var suspended = false

    init(dir: URL) {
        self.dir = dir
    }

    static func load(dir: URL = Store.dataDir().appendingPathComponent("clipboard")) -> Clipboard {
        let clipboard = Clipboard(dir: dir)
        let stored = Store.read(dir, indexFile).flatMap { try? JSONDecoder().decode([Clip].self, from: $0) } ?? []
        clipboard.items = stored.filter { FileManager.default.fileExists(atPath: clipboard.blob($0).path) }
        clipboard.dropOrphans()
        return clipboard
    }

    func start() {
        Timer.scheduledTimer(withTimeInterval: Self.interval, repeats: true) { _ in
            MainActor.assumeIsolated { self.poll() }
        }
    }

    private func poll() {
        let board = NSPasteboard.general
        guard !suspended, board.changeCount != seen else { return }
        seen = board.changeCount
        if let (kind, data) = Self.payload(board) {
            record(kind: kind, data: data, now: Store.now())
        }
    }

    func recent(_ query: String, now: Int64 = Store.now()) -> [Clip] {
        if sweep(now: now) {
            persist()
        }
        return Clips.query(query, clips: items)
    }

    func image(_ clip: Clip) -> URL? {
        clip.kind == .image ? blob(clip) : nil
    }

    func offer(_ digest: String, now: Int64 = Store.now()) -> Int? {
        guard let index = items.firstIndex(where: { $0.digest == digest }),
              let data = try? Data(contentsOf: blob(items[index])) else { return nil }
        let board = NSPasteboard.general
        board.clearContents()
        switch items[index].kind {
        case .text:
            board.setString(String(decoding: data, as: UTF8.self), forType: .string)
        case .image:
            board.setData(data, forType: .png)
        }
        seen = board.changeCount
        items[index].uses &+= 1
        items[index].lastUnix = now
        persist()
        return seen
    }

    func suspend() {
        suspended = true
    }

    func resume() {
        suspended = false
        seen = NSPasteboard.general.changeCount
    }

    @discardableResult
    func place(_ text: String) -> Int {
        let board = NSPasteboard.general
        board.clearContents()
        board.setString(text, forType: .string)
        return board.changeCount
    }

    func paste(_ change: Int?, into caller: NSRunningApplication?) {
        guard let change, let caller, caller.activate() else { return resume() }
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(150)) { [self] in
            if !caller.isTerminated,
               NSWorkspace.shared.frontmostApplication?.processIdentifier == caller.processIdentifier,
               NSPasteboard.general.changeCount == change {
                Self.synthesize(Self.pasteKey)
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(250)) { [self] in
                resume()
            }
        }
    }

    func capture(_ done: @escaping (String) -> Void) {
        guard !suspended else { return }
        guard Tile.granted() else { return done("") }
        suspend()
        let board = NSPasteboard.general
        let saved = (board.pasteboardItems ?? []).map(Self.duplicate)
        let before = board.changeCount
        Self.synthesize(Self.copyKey)
        awaitCopy(before: before, saved: saved, left: Self.copyTries, done: done)
    }

    private func awaitCopy(before: Int, saved: [NSPasteboardItem], left: Int,
                           done: @escaping (String) -> Void) {
        let board = NSPasteboard.general
        guard board.changeCount == before, left > 0 else {
            let text = board.changeCount == before ? "" : board.string(forType: .string) ?? ""
            board.clearContents()
            if !saved.isEmpty {
                board.writeObjects(saved)
            }
            resume()
            return done(trim(text))
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(20)) { [self] in
            awaitCopy(before: before, saved: saved, left: left - 1, done: done)
        }
    }

    private static func duplicate(_ item: NSPasteboardItem) -> NSPasteboardItem {
        let copy = NSPasteboardItem()
        for type in item.types {
            if let data = item.data(forType: type) {
                copy.setData(data, forType: type)
            }
        }
        return copy
    }

    private static func synthesize(_ key: CGKeyCode) {
        guard let source = CGEventSource(stateID: .combinedSessionState) else { return }
        for down in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: down)
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
    }

    func record(kind: ClipKind, data: Data, now: Int64) {
        let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        var added: Clip?
        if let index = items.firstIndex(where: { $0.digest == digest }) {
            items[index].lastUnix = now
        } else {
            let clip = Clip(digest: digest, kind: kind, bytes: data.count, lastUnix: now, uses: 1,
                            preview: kind == .text ? Clips.preview(String(decoding: data, as: UTF8.self)) : "")
            guard write(data, to: clip) else { return }
            items.append(clip)
            added = clip
        }
        sweep(now: now)
        if !persist(), let added {
            items.removeAll { $0.digest == added.digest }
            try? FileManager.default.removeItem(at: blob(added))
        }
    }

    @discardableResult
    private func sweep(now: Int64) -> Bool {
        let kept = Clips.retained(items, now: now)
        guard kept.count != items.count else { return false }
        let alive = Set(kept.map(\.digest))
        for clip in items where !alive.contains(clip.digest) {
            try? FileManager.default.removeItem(at: blob(clip))
        }
        items = kept
        return true
    }

    static func payload(_ board: NSPasteboard) -> (ClipKind, Data)? {
        let types = Set((board.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: ignoredTypes) else { return nil }
        if let text = board.string(forType: .string), !trim(text).isEmpty {
            return (.text, Data(text.utf8))
        }
        guard let png = png(board) else { return nil }
        return (.image, png)
    }

    private static func png(_ board: NSPasteboard) -> Data? {
        if let data = board.data(forType: .png) {
            return data
        }
        guard let tiff = board.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func blob(_ clip: Clip) -> URL {
        dir.appendingPathComponent(Self.blobDir).appendingPathComponent(clip.file)
    }

    private func write(_ data: Data, to clip: Clip) -> Bool {
        let target = blob(clip)
        guard (try? FileManager.default.createDirectory(at: target.deletingLastPathComponent(),
                                                        withIntermediateDirectories: true)) != nil,
              (try? data.write(to: target, options: .atomic)) != nil else { return false }
        return true
    }

    private func dropOrphans() {
        let blobs = dir.appendingPathComponent(Self.blobDir)
        let alive = Set(items.map(\.file))
        for name in (try? FileManager.default.contentsOfDirectory(atPath: blobs.path)) ?? []
            where !alive.contains(name)
        {
            try? FileManager.default.removeItem(at: blobs.appendingPathComponent(name))
        }
    }

    @discardableResult
    private func persist() -> Bool {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        guard let data = try? encoder.encode(items) else { return false }
        return Store.write(dir, Self.indexFile, data)
    }
}
